/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCommunityCommunityIdRouteImport } from './routes/_authenticated/community/$communityId'
import { Route as AuthenticatedCommunityCommunityIdChannelChannelIdRouteImport } from './routes/_authenticated/community/$communityId/channel/$channelId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityCommunityIdRoute =
  AuthenticatedCommunityCommunityIdRouteImport.update({
    id: '/community/$communityId',
    path: '/community/$communityId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommunityCommunityIdChannelChannelIdRoute =
  AuthenticatedCommunityCommunityIdChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => AuthenticatedCommunityCommunityIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/community/$communityId': typeof AuthenticatedCommunityCommunityIdRouteWithChildren
  '/community/$communityId/channel/$channelId': typeof AuthenticatedCommunityCommunityIdChannelChannelIdRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/community/$communityId': typeof AuthenticatedCommunityCommunityIdRouteWithChildren
  '/community/$communityId/channel/$channelId': typeof AuthenticatedCommunityCommunityIdChannelChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/community/$communityId': typeof AuthenticatedCommunityCommunityIdRouteWithChildren
  '/_authenticated/community/$communityId/channel/$channelId': typeof AuthenticatedCommunityCommunityIdChannelChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/settings'
    | '/community/$communityId'
    | '/community/$communityId/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/login'
    | '/settings'
    | '/'
    | '/community/$communityId'
    | '/community/$communityId/channel/$channelId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/login'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/community/$communityId'
    | '/_authenticated/community/$communityId/channel/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/$communityId': {
      id: '/_authenticated/community/$communityId'
      path: '/community/$communityId'
      fullPath: '/community/$communityId'
      preLoaderRoute: typeof AuthenticatedCommunityCommunityIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community/$communityId/channel/$channelId': {
      id: '/_authenticated/community/$communityId/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/community/$communityId/channel/$channelId'
      preLoaderRoute: typeof AuthenticatedCommunityCommunityIdChannelChannelIdRouteImport
      parentRoute: typeof AuthenticatedCommunityCommunityIdRoute
    }
  }
}

interface AuthenticatedCommunityCommunityIdRouteChildren {
  AuthenticatedCommunityCommunityIdChannelChannelIdRoute: typeof AuthenticatedCommunityCommunityIdChannelChannelIdRoute
}

const AuthenticatedCommunityCommunityIdRouteChildren: AuthenticatedCommunityCommunityIdRouteChildren =
  {
    AuthenticatedCommunityCommunityIdChannelChannelIdRoute:
      AuthenticatedCommunityCommunityIdChannelChannelIdRoute,
  }

const AuthenticatedCommunityCommunityIdRouteWithChildren =
  AuthenticatedCommunityCommunityIdRoute._addFileChildren(
    AuthenticatedCommunityCommunityIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCommunityCommunityIdRoute: typeof AuthenticatedCommunityCommunityIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCommunityCommunityIdRoute:
    AuthenticatedCommunityCommunityIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
