/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPodPodIdRouteImport } from './routes/_authenticated/pod/$podId'
import { Route as AuthenticatedPodPodIdCommunityCommunityIdRouteImport } from './routes/_authenticated/pod/$podId/community/$communityId'
import { Route as AuthenticatedPodPodIdCommunityCommunityIdChannelChannelIdRouteImport } from './routes/_authenticated/pod/$podId/community/$communityId/channel/$channelId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPodPodIdRoute = AuthenticatedPodPodIdRouteImport.update({
  id: '/pod/$podId',
  path: '/pod/$podId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPodPodIdCommunityCommunityIdRoute =
  AuthenticatedPodPodIdCommunityCommunityIdRouteImport.update({
    id: '/community/$communityId',
    path: '/community/$communityId',
    getParentRoute: () => AuthenticatedPodPodIdRoute,
  } as any)
const AuthenticatedPodPodIdCommunityCommunityIdChannelChannelIdRoute =
  AuthenticatedPodPodIdCommunityCommunityIdChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => AuthenticatedPodPodIdCommunityCommunityIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/pod/$podId': typeof AuthenticatedPodPodIdRouteWithChildren
  '/pod/$podId/community/$communityId': typeof AuthenticatedPodPodIdCommunityCommunityIdRouteWithChildren
  '/pod/$podId/community/$communityId/channel/$channelId': typeof AuthenticatedPodPodIdCommunityCommunityIdChannelChannelIdRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/pod/$podId': typeof AuthenticatedPodPodIdRouteWithChildren
  '/pod/$podId/community/$communityId': typeof AuthenticatedPodPodIdCommunityCommunityIdRouteWithChildren
  '/pod/$podId/community/$communityId/channel/$channelId': typeof AuthenticatedPodPodIdCommunityCommunityIdChannelChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/pod/$podId': typeof AuthenticatedPodPodIdRouteWithChildren
  '/_authenticated/pod/$podId/community/$communityId': typeof AuthenticatedPodPodIdCommunityCommunityIdRouteWithChildren
  '/_authenticated/pod/$podId/community/$communityId/channel/$channelId': typeof AuthenticatedPodPodIdCommunityCommunityIdChannelChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/signup'
    | '/settings'
    | '/pod/$podId'
    | '/pod/$podId/community/$communityId'
    | '/pod/$podId/community/$communityId/channel/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/login'
    | '/signup'
    | '/settings'
    | '/'
    | '/pod/$podId'
    | '/pod/$podId/community/$communityId'
    | '/pod/$podId/community/$communityId/channel/$channelId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/login'
    | '/signup'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/pod/$podId'
    | '/_authenticated/pod/$podId/community/$communityId'
    | '/_authenticated/pod/$podId/community/$communityId/channel/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pod/$podId': {
      id: '/_authenticated/pod/$podId'
      path: '/pod/$podId'
      fullPath: '/pod/$podId'
      preLoaderRoute: typeof AuthenticatedPodPodIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pod/$podId/community/$communityId': {
      id: '/_authenticated/pod/$podId/community/$communityId'
      path: '/community/$communityId'
      fullPath: '/pod/$podId/community/$communityId'
      preLoaderRoute: typeof AuthenticatedPodPodIdCommunityCommunityIdRouteImport
      parentRoute: typeof AuthenticatedPodPodIdRoute
    }
    '/_authenticated/pod/$podId/community/$communityId/channel/$channelId': {
      id: '/_authenticated/pod/$podId/community/$communityId/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/pod/$podId/community/$communityId/channel/$channelId'
      preLoaderRoute: typeof AuthenticatedPodPodIdCommunityCommunityIdChannelChannelIdRouteImport
      parentRoute: typeof AuthenticatedPodPodIdCommunityCommunityIdRoute
    }
  }
}

interface AuthenticatedPodPodIdCommunityCommunityIdRouteChildren {
  AuthenticatedPodPodIdCommunityCommunityIdChannelChannelIdRoute: typeof AuthenticatedPodPodIdCommunityCommunityIdChannelChannelIdRoute
}

const AuthenticatedPodPodIdCommunityCommunityIdRouteChildren: AuthenticatedPodPodIdCommunityCommunityIdRouteChildren =
  {
    AuthenticatedPodPodIdCommunityCommunityIdChannelChannelIdRoute:
      AuthenticatedPodPodIdCommunityCommunityIdChannelChannelIdRoute,
  }

const AuthenticatedPodPodIdCommunityCommunityIdRouteWithChildren =
  AuthenticatedPodPodIdCommunityCommunityIdRoute._addFileChildren(
    AuthenticatedPodPodIdCommunityCommunityIdRouteChildren,
  )

interface AuthenticatedPodPodIdRouteChildren {
  AuthenticatedPodPodIdCommunityCommunityIdRoute: typeof AuthenticatedPodPodIdCommunityCommunityIdRouteWithChildren
}

const AuthenticatedPodPodIdRouteChildren: AuthenticatedPodPodIdRouteChildren = {
  AuthenticatedPodPodIdCommunityCommunityIdRoute:
    AuthenticatedPodPodIdCommunityCommunityIdRouteWithChildren,
}

const AuthenticatedPodPodIdRouteWithChildren =
  AuthenticatedPodPodIdRoute._addFileChildren(
    AuthenticatedPodPodIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPodPodIdRoute: typeof AuthenticatedPodPodIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPodPodIdRoute: AuthenticatedPodPodIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
