/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/.well-known/openid-configuration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["openid_configuration"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/oidc/sia": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** `POST /api/v1/oidc/sia` — Issue a Signed Identity Assertion for a target Pod. */
    post: operations["issue_sia"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pods": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** `GET /api/v1/pods` — List active pods. */
    get: operations["list_pods"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pods/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** `POST /api/v1/pods/register` — Register a new Pod. */
    post: operations["register_pod"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pods/{pod_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** `GET /api/v1/pods/{pod_id}` — Get a single pod's details. */
    get: operations["get_pod"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/pods/{pod_id}/heartbeat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * `POST /api/v1/pods/{pod_id}/heartbeat` — Record a Pod heartbeat.
     * @description Authenticated via the Pod's `client_id`/`client_secret` pair sent as a
     *     Bearer token (the `client_secret` value). For Phase 1 we look the pod up
     *     by its id and verify the secret from the `Authorization` header.
     */
    post: operations["heartbeat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_user"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/@me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** `GET /api/v1/users/@me` — Return the current user's full profile. */
    get: operations["get_me"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** `PATCH /api/v1/users/@me` — Update the current user's profile. */
    patch: operations["update_me"];
    trace?: never;
  };
  "/api/v1/users/@me/pods": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** `GET /api/v1/users/@me/pods` — List Pods the current user has bookmarked. */
    get: operations["get_my_pods"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** `GET /api/v1/users/{user_id}` — Return a user's public profile. */
    get: operations["get_user"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oidc/.well-known/jwks.json": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["jwks"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oidc/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Render a minimal HTML login form.
     *     The SPA would typically collect credentials and POST here.
     */
    get: operations["authorize"];
    put?: never;
    /** Process login form — validate credentials, generate auth code, redirect. */
    post: operations["authorize_submit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oidc/revoke": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["revoke"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oidc/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["token"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/oidc/userinfo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["userinfo"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Structured API error returned to clients. */
    ApiErrorBody: {
      error: components["schemas"]["ApiErrorDetail"];
    };
    ApiErrorDetail: {
      code: string;
      details?: components["schemas"]["FieldError"][] | null;
      message: string;
    };
    /** @description POST /api/v1/users — Register a new user. */
    CreateUserRequest: {
      display_name: string;
      email?: string | null;
      password: string;
      username: string;
    };
    FieldError: {
      field: string;
      message: string;
    };
    HealthResponse: {
      status: string;
    };
    HeartbeatRequest: {
      /** Format: int32 */
      community_count?: number | null;
      /** Format: int32 */
      member_count?: number | null;
      /** Format: int32 */
      online_count?: number | null;
      version?: string | null;
    };
    HeartbeatResponse: {
      ok: boolean;
      recorded_at: string;
    };
    /** @description A single JSON Web Key. */
    JwkKey: {
      crv: string;
      kid: string;
      kty: string;
      use: string;
      x: string;
    };
    /** @description JSON Web Key Set response. */
    JwksResponse: {
      keys: components["schemas"]["JwkKey"][];
    };
    ListPodsQuery: {
      after?: string | null;
      before?: string | null;
      /** Format: int64 */
      limit?: number;
      sort?: string;
    };
    ListPodsResponse: {
      data: components["schemas"]["PodResponse"][];
      has_more: boolean;
    };
    MyPodsResponse: {
      data: components["schemas"]["PodResponse"][];
    };
    /** @description OpenID Connect discovery document. */
    OpenIdConfiguration: {
      authorization_endpoint: string;
      code_challenge_methods_supported: string[];
      grant_types_supported: string[];
      id_token_signing_alg_values_supported: string[];
      issuer: string;
      jwks_uri: string;
      response_types_supported: string[];
      revocation_endpoint: string;
      scopes_supported: string[];
      subject_types_supported: string[];
      token_endpoint: string;
      token_endpoint_auth_methods_supported: string[];
      userinfo_endpoint: string;
    };
    /** @description Registration response — includes the client credentials (returned only once). */
    PodRegistrationResponse: {
      client_id: string;
      client_secret: string;
      pod_id: string;
      /** Format: date-time */
      registered_at: string;
      status: string;
    };
    /** @description Public-facing pod response (no sensitive fields). */
    PodResponse: {
      capabilities: string[];
      /** Format: int32 */
      community_count: number;
      /** Format: date-time */
      created_at: string;
      description?: string | null;
      icon_url?: string | null;
      id: string;
      /** Format: date-time */
      last_heartbeat?: string | null;
      /** Format: int32 */
      max_members: number;
      /** Format: int32 */
      member_count: number;
      name: string;
      /** Format: int32 */
      online_count: number;
      owner_id: string;
      public: boolean;
      region?: string | null;
      status: string;
      /** Format: date-time */
      updated_at: string;
      url: string;
      version?: string | null;
    };
    /** @description Public-facing user profile (excludes email, status, updated_at). */
    PublicUserResponse: {
      avatar_url?: string | null;
      /** Format: date-time */
      created_at: string;
      display_name: string;
      /** Format: int64 */
      flags: number;
      id: string;
      username: string;
    };
    RegisterPodRequest: {
      capabilities?: string[];
      description?: string | null;
      icon_url?: string | null;
      /** Format: int32 */
      max_members?: number;
      name: string;
      public?: boolean;
      region?: string | null;
      url: string;
      version?: string | null;
    };
    RevokeRequest: {
      token: string;
      token_type_hint?: string | null;
    };
    SiaRequest: {
      pod_id: string;
    };
    SiaResponse: {
      expires_at: string;
      sia: string;
    };
    TokenRequest: {
      client_id?: string | null;
      code?: string | null;
      code_verifier?: string | null;
      grant_type: string;
      redirect_uri?: string | null;
      refresh_token?: string | null;
    };
    TokenResponse: {
      access_token: string;
      /** Format: int64 */
      expires_in: number;
      id_token?: string | null;
      refresh_token?: string | null;
      scope: string;
      token_type: string;
    };
    UpdateProfileRequest: {
      avatar_url?: string | null;
      display_name?: string | null;
    };
    /** @description Public-facing user response (no sensitive fields). */
    UserResponse: {
      avatar_url?: string | null;
      /** Format: date-time */
      created_at: string;
      display_name: string;
      email?: string | null;
      email_verified: boolean;
      /** Format: int64 */
      flags: number;
      id: string;
      status: string;
      /** Format: date-time */
      updated_at: string;
      username: string;
    };
    /** @description UserInfo endpoint response. */
    UserinfoResponse: {
      email?: string | null;
      email_verified?: boolean | null;
      name?: string | null;
      picture?: string | null;
      preferred_username?: string | null;
      sub: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  openid_configuration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OpenID Connect discovery document */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OpenIdConfiguration"];
        };
      };
    };
  };
  issue_sia: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SiaRequest"];
      };
    };
    responses: {
      /** @description SIA issued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiaResponse"];
        };
      };
      /** @description Invalid pod_id */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Missing pods scope */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Pod not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  list_pods: {
    parameters: {
      query?: {
        /** @description Sort order: popular or newest */
        sort?: string;
        /** @description Cursor: fetch pods before this ID */
        before?: string;
        /** @description Cursor: fetch pods after this ID */
        after?: string;
        /** @description Number of pods to return (1-100, default 25) */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of pods */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListPodsResponse"];
        };
      };
    };
  };
  register_pod: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterPodRequest"];
      };
    };
    responses: {
      /** @description Pod registered */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PodRegistrationResponse"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_pod: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Pod ID */
        pod_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Pod details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PodResponse"];
        };
      };
      /** @description Pod not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  heartbeat: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Pod ID */
        pod_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HeartbeatRequest"];
      };
    };
    responses: {
      /** @description Heartbeat recorded */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HeartbeatResponse"];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Pod not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  create_user: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"];
      };
    };
    responses: {
      /** @description User created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Username or email conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  update_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileRequest"];
      };
    };
    responses: {
      /** @description Updated user profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_my_pods: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Bookmarked pods */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MyPodsResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  get_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User ID */
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Public user profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicUserResponse"];
        };
      };
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  jwks: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON Web Key Set */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JwksResponse"];
        };
      };
    };
  };
  authorize: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Login form */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": unknown;
        };
      };
    };
  };
  authorize_submit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect with auth code */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  revoke: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RevokeRequest"];
      };
    };
    responses: {
      /** @description Token revoked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  token: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRequest"];
      };
    };
    responses: {
      /** @description Token response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
  userinfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserinfoResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiErrorBody"];
        };
      };
    };
  };
}
